apiVersion: v1
kind: Service
metadata:
  name: tlapp-service
spec:
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000
  selector:
    app: tlapp
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tlapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: tlapp
  template:
    metadata:
      labels:
        app: tlapp
    spec:
      containers:
      - name: tlapp
        image: waven7/tlapp:latest
        # image: tlapp:latest #use this and the row under for local testing
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        env:
          - name: MYSQL_HOST
            value: "mysql-service"
          - name: MYSQL_USER
            value: "root"
          - name: MYSQL_PASSWORD
            value: "password123"
          - name: MYSQL_DB
            value: "tlapp"